---
settings:
  name: NetApp container solutions
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: true
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-containers.zip
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: 컨테이너 솔루션
    url: "/index.html"
  - title: 새로운 소식
    url: "/whats-new.html"
  - section: anthos
  - section: openshift
  - section: openshift-aws
  - section: tanzu
  - title: 비디오
    url: "/videos/index.html"
    entries:
    - title: 안토스
      url: "/videos/anthos-videos.html"
    - title: 레드햇 오픈시프트
      url: "/videos/openshift-videos.html"
    - title: VMware Tanzu
      url: "/videos/tanzu-videos.html"
  - title: 블로그
    url: "/blogs.html"
  - title: 법적 고지 사항
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
