---
sidebar: sidebar 
permalink: vsphere-kubernetes-service/vks-overview.html 
keywords: vks, vSphere Kubernetes Service, ONTAP, kubernetes, overview 
summary: vSphere Kubernetes Service와 컨테이너화된 워크로드를 위한 NetApp ONTAP과의 통합 방법에 대해 알아보십시오. 
---
= VMware vSphere Kubernetes Service와 NetApp ONTAP에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vSphere Kubernetes Service(VKS)는 VMware에서 제공하는 관리형 Kubernetes 솔루션으로, 기업에서 Kubernetes를 사용하여 컨테이너화된 애플리케이션을 배포, 관리 및 확장할 수 있도록 지원합니다. NetApp ONTAP 스토리지와 함께 사용하면 VKS는 클라우드 네이티브 워크로드에 엔터프라이즈급 영구 스토리지, 성능 및 데이터 관리 기능을 제공합니다.

VKS는 VMware Cloud Foundation(VCF)에 내장되어 있으며 업스트림 CNCF Kubernetes를 준수하여 더 넓은 Kubernetes 생태계 및 툴과의 호환성을 보장합니다.



[[key-features-of-vsphere-kubernetes-service]]
== vSphere Kubernetes 서비스의 주요 기능

. *관리형 Kubernetes 클러스터:* vSphere Kubernetes Service는 Kubernetes 클러스터의 배포 및 관리를 간소화합니다. 클러스터 생성, 업그레이드, 확장 및 모니터링과 같은 작업을 자동화합니다.
. *VMware 인프라와의 통합:* VKS는 VMware vSphere, NSX-T 및 기타 VMware 솔루션과 원활하게 통합되어 조직이 기존 VMware 인프라를 Kubernetes 워크로드에 활용할 수 있도록 지원합니다.
. *멀티 클라우드 및 하이브리드 클라우드 지원:* vSphere Kubernetes Service는 프라이빗 클라우드, 퍼블릭 클라우드(예: AWS, Azure, Google Cloud) 및 하이브리드 클라우드 환경에 배포를 지원하여 조직이 애플리케이션을 유연하게 관리할 수 있도록 합니다.
. *내장 보안:* VKS에는 역할 기반 액세스 제어(RBAC), 정책 시행, 네트워크 보안을 위한 VMware NSX와의 통합 등 보안 기능이 포함되어 있습니다.
. *Kubernetes 생태계 지원:* VKS는 완전한 업스트림 Kubernetes API를 지원하여 환경 간 이식성을 보장하고, 서비스 메시용 Istio, 모니터링용 Prometheus 및 기타 CNCF 인증 툴 등 광범위한 Kubernetes 생태계와의 호환성을 제공합니다. 조직은 표준 Kubernetes 기술 및 통합 기능을 VKS 클러스터에 직접 적용할 수 있습니다.
. *개발자 친화적인 툴:* VKS는 CI/CD 파이프라인, GitOps 모범 사례, kubectl 및 Helm과 같은 툴을 포함한 표준 Kubernetes 개발자 워크플로를 지원하므로 개발 팀은 독자적인 인터페이스를 학습하지 않고도 컨테이너화된 애플리케이션을 구축하고 배포할 수 있습니다.
. *확장성 및 고가용성:* VKS는 자동 확장 및 내결함성과 같은 기능을 제공하여 애플리케이션의 높은 가용성과 성능을 보장합니다.
. *관찰 가능성 및 모니터링:* VKS는 표준 Kubernetes 호환 모니터링 툴과 통합하여 클러스터 및 애플리케이션 성능에 대한 실시간 인사이트를 제공합니다.




[[use-cases-for-vsphere-kubernetes-service]]
== vSphere Kubernetes Service의 사용 사례

. *애플리케이션 현대화:* 조직은 기존 애플리케이션을 컨테이너화하고 VKS에서 관리하는 Kubernetes 클러스터에 배포함으로써 현대화할 수 있습니다.
. *DevOps 활성화:* VKS는 자동화, CI/CD 통합 및 개발자 친화적인 툴을 제공하여 DevOps 워크플로우를 지원합니다.
. *하이브리드 클라우드 배포:* 기업은 VKS를 사용하여 온프레미스 및 클라우드 환경 전반에 걸쳐 Kubernetes 클러스터를 배포하고 일관된 운영을 구현할 수 있습니다.
. *마이크로서비스 아키텍처:* VKS는 마이크로서비스 기반 애플리케이션 개발을 지원하여 팀이 분산 시스템을 구축하고 확장할 수 있도록 합니다.

