---
sidebar: sidebar 
permalink: tanzu/vtwn-solution-overview.html 
keywords: VMware Tanzu, Tanzu, DevOps, Netapp, Trident, Trident Protect 
summary: '이 참조 문서는 NetApp에서 검증한 대로 다양한 데이터 센터 환경에서 Tanzu Kubernetes Grid(TKG), Tanzu Kubernetes Grid Service(TKGS) 또는 Tanzu Kubernetes Grid Integrated(TKGI)로 배포된 다양한 VMware Tanzu Kubernetes 솔루션의 배포 검증을 제공 NetApp.' 
---
= NVA-1166: NetApp 사용한 VMware Tanzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Alan Cowles와 Nikhil M Kulkarni, NetApp

[role="lead"]
이 참조 문서는 NetApp에서 검증한 대로 다양한 데이터 센터 환경에서 Tanzu Kubernetes Grid(TKG), Tanzu Kubernetes Grid Service(TKGS) 또는 Tanzu Kubernetes Grid Integrated(TKGI)로 배포된 다양한 VMware Tanzu Kubernetes 솔루션의 배포 검증을 제공 NetApp.  또한 NetApp 스토리지 시스템과 Trident 스토리지 오케스트레이터를 통한 스토리지 통합에 대해서도 설명하고, 이를 통해 영구 스토리지를 관리하고, Trident Protect를 통해 해당 영구 스토리지를 사용하여 상태 저장 애플리케이션을 백업하고 복제하는 방법에 대해서도 설명합니다.  마지막으로 이 문서에서는 솔루션 통합 및 검증에 대한 비디오 데모를 제공합니다.



== 사용 사례

NetApp 솔루션이 포함된 VMware Tanzu는 다음과 같은 사용 사례를 가진 고객에게 탁월한 가치를 제공하도록 설계되었습니다.

* VMware vSphere에 배포되고 NetApp 스토리지 시스템과 통합된 VMware Tanzu Kubernetes Grid 제품은 배포 및 관리가 쉽습니다.
* VMware Tanzu Kubernetes Grid 제품을 통해 엔터프라이즈 컨테이너와 가상화된 워크로드의 결합된 성능을 경험해 보세요.
* NetApp 스토리지 및 NetApp Trident 제품군과 함께 사용할 때 VMware Tanzu의 기능을 강조하는 실제 구성 및 사용 사례입니다.
* Trident Protect를 사용하여 NetApp 스토리지 시스템에 데이터가 있는 VMware Tanzu Kubernetes Grid 클러스터에 배포된 컨테이너화된 워크로드를 애플리케이션 일관성 있게 보호하거나 마이그레이션합니다.




== 사업적 가치

기업들은 새로운 제품을 만들고, 출시 주기를 단축하고, 새로운 기능을 빠르게 추가하기 위해 DevOps 방식을 점점 더 많이 도입하고 있습니다.  컨테이너와 마이크로서비스는 본질적으로 민첩한 특성으로 인해 DevOps 실무를 지원하는 데 중요한 역할을 합니다.  그러나 기업 환경에서 프로덕션 규모로 DevOps를 실행하는 것은 고유한 과제를 제시하며, 다음과 같은 기본 인프라에 특정 요구 사항을 부과합니다.

* 스택의 모든 계층에서 높은 가용성
* 배포 절차의 용이성
* 중단 없는 운영 및 업그레이드
* 마이크로서비스 민첩성을 유지하기 위한 API 기반 및 프로그래밍 가능 인프라
* 성능 보장이 있는 멀티테넌시
* 가상화된 워크로드와 컨테이너화된 워크로드를 동시에 실행할 수 있는 기능
* 작업 부하 수요에 따라 인프라를 독립적으로 확장할 수 있는 기능
* 온프레미스 데이터 센터와 클라우드 모두에서 컨테이너를 실행하여 하이브리드 클라우드 모델로 배포할 수 있는 기능입니다.


NetApp 의 VMware Tanzu는 이러한 과제를 인식하고 고객이 선택한 하이브리드 클라우드 환경에서 VMware Tanzu Kubernetes 제품을 배포하여 각 문제를 해결하는 솔루션을 제시합니다.



== 기술 개요

NetApp 솔루션이 포함된 VMware Tanzu는 다음과 같은 주요 구성 요소로 구성됩니다.



=== VMware Tanzu Kubernetes 플랫폼

VMware Tanzu는 NetApp 의 솔루션 엔지니어링 팀이 실험실에서 검증한 다양한 버전으로 제공됩니다.  각 Tanzu 릴리스는 NetApp 스토리지 포트폴리오와 성공적으로 통합되며, 각각 특정 인프라 요구 사항을 충족하는 데 도움이 될 수 있습니다.  다음의 주요 내용은 이 문서에서 설명하는 Tanzu의 각 버전의 기능과 제공 사항을 설명합니다.

*VMware Tanzu Kubernetes Grid(TKG)*

* VMware vSphere 환경에 배포된 표준 업스트림 Kubernetes 환경입니다.
* 이전에는 Essential PKS(2019년 2월 Heptio 인수)로 알려짐.
* TKG는 vSphere 6.7U3 이상 지원을 위해 별도의 관리 클러스터 인스턴스와 함께 배포됩니다.
* TKG 배포는 AWS나 Azure를 통해 클라우드에도 배포할 수 있습니다.
* Windows 또는 Linux 워커 노드(Ubuntu/Photon)를 사용할 수 있습니다.
* 제어 평면에는 NSX-T, HA 프록시, AVI 네트워킹 또는 로드 밸런서를 사용할 수 있습니다.
* TKG는 애플리케이션/데이터 플레인에 MetalLB를 지원합니다.
* vSphere CSI는 물론 NetApp Trident 와 같은 타사 CSI도 사용할 수 있습니다.


*VMware Tanzu Kubernetes Grid 서비스(TKGS)*

* VMware vSphere 환경에 배포된 표준 업스트림 Kubernetes 환경입니다.
* 이전에는 Essential PKS(2019년 2월 Heptio 인수)로 알려짐.
* TKGS는 vSphere 7.0U1 이상에서 슈퍼바이저 클러스터 및 워크로드 클러스터와 함께 배포되었습니다.
* Windows 또는 Linux 워커 노드(Ubuntu/Photon)를 사용할 수 있습니다.
* 제어 평면에는 NSX-T, HA 프록시, AVI 네트워킹 또는 로드 밸런서를 사용할 수 있습니다.
* TKGS는 애플리케이션/데이터 플레인에 대해 MetalLB를 지원합니다.
* vSphere CSI는 물론 NetApp Trident 와 같은 타사 CSI도 사용할 수 있습니다.
* Tanzu와 함께 vSphere Pod에 대한 지원을 제공하여 환경 내에서 활성화된 ESXi 호스트에서 Pod를 직접 실행할 수 있습니다.


*VMWare Tanzu Kubernetes Grid 통합(TKGI)*

* 이전에는 Enterprise PKS(2019년 2월 Heptio 인수)로 알려짐.
* NSX-T, HA 프록시 또는 Avi를 사용할 수 있습니다.  또한, 자체 로드 밸런서를 제공할 수도 있습니다.
* vSphere 6.7U3 이상, AWS, Azure, GCP에서 지원됩니다.
* 마법사를 통한 설정으로 배포가 간편합니다.
* BOSH가 관리하는 제어된 변경 불가능한 VM에서 Tanzu를 실행합니다.
* vSphere CSI는 물론 NetApp Trident 와 같은 타사 CSI도 사용할 수 있습니다(일부 조건이 적용됨).


*Tanzu가 포함된 vSphere(vSphere Pod)*

* vSphere 기반 포드는 완전한 격리를 위해 지정된 가상 하드웨어를 갖춘 얇은 광자 기반 계층에서 실행됩니다.
* NSX-T가 필요하지만 Harbor 이미지 레지스트리와 같은 추가 기능 지원이 가능합니다.
* TKGS와 같은 가상 Supervisor 클러스터를 사용하여 vSphere 7.0U1 이상에서 배포 및 관리됩니다.  ESXi 노드에서 직접 Pod를 실행합니다.
* vSphere와 완벽하게 통합되어 vSphere 관리자를 통해 가시성과 제어력이 매우 뛰어납니다.
* 최고 수준의 보안을 위해 분리된 CRX 기반 포드.
* 영구 저장소의 경우 vSphere CSI만 지원합니다.  타사 스토리지 오케스트레이터는 지원되지 않습니다.




=== NetApp 스토리지 시스템

NetApp 기업 데이터 센터와 하이브리드 클라우드 구축에 적합한 여러 가지 스토리지 시스템을 보유하고 있습니다.  NetApp 포트폴리오에는 NetApp ONTAP, NetApp Element, NetApp e-Series 스토리지 시스템이 포함되어 있으며, 이 모든 시스템은 컨테이너화된 애플리케이션에 대한 영구 스토리지를 제공할 수 있습니다.

자세한 내용은 NetApp 웹사이트를 방문하세요. https://www.netapp.com["여기"] .



=== NetApp 스토리지 통합

Trident VMware Tanzu를 포함한 컨테이너와 Kubernetes 배포판을 위한 오픈 소스의 완벽하게 지원되는 스토리지 오케스트레이터입니다.

자세한 내용은 Trident 웹사이트를 방문하세요. https://docs.netapp.com/us-en/trident/index.html["여기"] .



== 검증된 릴리스에 대한 현재 지원 매트릭스

|===


| 기술 | 목적 | 소프트웨어 버전 


| NetApp ONTAP | 스토리지 | 9.9.1 


| NetApp Trident | 스토리지 오케스트레이션 | 22.04.0 


| VMware Tanzu Kubernetes Grid | 컨테이너 오케스트레이션 | 1.4+ 


.2+| VMware Tanzu Kubernetes 그리드 서비스 .2+| 컨테이너 오케스트레이션 | 0.0.15 [vSphere 네임스페이스] 


| 1.22.6 [슈퍼바이저 클러스터 쿠버네티스] 


| VMware Tanzu Kubernetes Grid 통합 | 컨테이너 오케스트레이션 | 1.13.3 


| VMware vSphere | 데이터 센터 가상화 | 7.0U3 


| VMware NSX-T 데이터 센터 | 네트워킹 및 보안 | 3.1.3 


| VMware NSX 고급 로드 밸런서 | 로드 밸런서 | 20.1.3 
|===