---
sidebar: sidebar 
permalink: anthos/anthos-storint-overview.html 
keywords: Trident, Trident, persistent storage 
summary: NetApp Anthos와 같은 컨테이너 기반 환경에서 영구 데이터를 조정하고 관리하는 데 도움이 되는 다양한 제품을 제공합니다. 
---
= NetApp 스토리지 통합 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Anthos와 같은 컨테이너 기반 환경에서 영구 데이터를 조정하고 관리하는 데 도움이 되는 다양한 제품을 제공합니다.



== Anthos Ready 스토리지 파트너 프로그램.

Google Cloud에서는 Anthos Ready 스토리지 파트너 프로그램을 통해 Anthos의 새로운 릴리스와 파트너 스토리지 통합에 대한 업데이트된 유효성 검사를 주기적으로 요청합니다.  현재 검증된 스토리지 솔루션, CSI 드라이버, 사용 가능한 기능 및 지원되는 Anthos 버전 목록을 찾을 수 있습니다. https://cloud.google.com/anthos/docs/resources/partner-storage["여기"^] .

NetApp Anthos 버전을 사용하여 Trident CSI 호환 스토리지 오케스트레이터와 ONTAP 스토리지 시스템을 검증해 달라는 요청에 따라 분기별로 정기적으로 규정을 준수해 왔습니다.

다음 표에는 Anthos Ready 스토리지 파트너 프로그램의 일부로 NetApp Trident CSI 드라이버와 기능 세트의 검증을 위해 NetApp 과 NetApp 파트너 엔지니어가 테스트한 Anthos 버전이 포함되어 있습니다.

|===


| 배포 유형 | 버전 | 저장 시스템 | Trident 버전 | 규약 | 특징 


| VMware | 1.28 | ONTAP 9.12.1 | 24.02 | NAS | 멀티라이터, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.28 | ONTAP 9.12.1 | 24.02 | SAN | 원시 블록, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | NAS | 멀티라이터, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | SAN | 원시 블록, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | NAS | 멀티라이터, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | SAN | 원시 블록, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | NAS | 멀티라이터, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | SAN | 원시 블록, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | NAS | 멀티라이터, 볼륨 확장, 스냅샷 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | SAN | 원시 블록, 볼륨 확장, 스냅샷 


| VMware | 1.11 | 원소 12.3 | 22.04 | SAN | 원시 블록, 볼륨 확장, 스냅샷 


| 베어 메탈 | 1.10 | ONTAP 9.8 | 22.01 | NAS | 멀티라이터, 볼륨 확장, 스냅샷 


| 베어 메탈 | 1.10 | ONTAP 9.8 | 22.01 | SAN | 원시 블록, 볼륨 확장, 스냅샷 
|===


== NetApp 스토리지 통합

NetApp Anthos와 같은 컨테이너 기반 환경에서 영구 데이터를 조정하고 관리하는 데 도움이 되는 다양한 제품을 제공합니다.

NetApp Trident Anthos를 포함한 컨테이너와 Kubernetes 배포판을 위한 오픈 소스의 완벽하게 지원되는 스토리지 오케스트레이터입니다.  자세한 내용은 Trident 웹사이트를 방문하세요. https://docs.netapp.com/us-en/trident/index.html["여기"] .

다음 페이지에는 Anthos with NetApp 솔루션에서 애플리케이션 및 영구 스토리지 관리를 위해 검증된 NetApp 제품에 대한 추가 정보가 있습니다.
