---
sidebar: sidebar 
permalink: anthos/anthos-trident-ontap-nfs.html 
keywords: Trident, Trident, ONTAP, AFF, FAS, NFS 
summary: NetApp ONTAP 스토리지 시스템과 Trident 통합을 활성화하려면 스토리지 시스템과의 통신을 지원하는 백엔드를 만들어야 합니다. 
---
= NetApp ONTAP NFS 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ONTAP 스토리지 시스템과 Trident 통합을 활성화하려면 스토리지 시스템과의 통신을 지원하는 백엔드를 만들어야 합니다.

. 다운로드한 설치 아카이브에는 샘플 백엔드 파일이 있습니다. `sample-input` 폴더 계층구조.  NFS를 제공하는 NetApp ONTAP 시스템의 경우 다음을 복사하십시오. `backend-ontap-nas.json` 작업 디렉토리에 파일을 복사하고 편집하세요.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/backends-samples/ontap-nas/backend-ontap-nas.json ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi backend-ontap-nas.json
----
. 이 파일에서 backendName, managementLIF, dataLIF, svm, username 및 password 값을 편집합니다.
+
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "ontap-nas+10.61.181.221",
    "managementLIF": "172.21.224.201",
    "dataLIF": "10.61.181.221",
    "svm": "trident_svm",
    "username": "cluster-admin",
    "password": "password"
}
----
+

NOTE: 쉽게 식별할 수 있도록 NFS를 제공하는 storageDriverName과 dataLIF의 조합으로 사용자 지정 backendName 값을 정의하는 것이 가장 좋습니다.

. 백엔드 파일이 준비되면 다음 명령을 실행하여 첫 번째 백엔드를 만듭니다.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-nas.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| ontap-nas+10.61.181.221 | ontap-nas      | be7a619d-c81d-445c-b80c-5c87a73c5b1e | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. 백엔드를 만든 후에는 다음으로 스토리지 클래스를 만들어야 합니다.  백엔드와 마찬가지로, sample-inputs 폴더에서 해당 환경에 맞게 편집할 수 있는 샘플 스토리지 클래스 파일이 있습니다.  작업 디렉토리에 복사하고 생성된 백엔드를 반영하도록 필요한 편집을 합니다.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi storage-class-basic.yaml
----
. 이 파일에 대해 해야 할 유일한 편집은 다음을 정의하는 것입니다. `backendType` 새로 생성된 백엔드의 스토리지 드라이버 이름에 대한 값입니다.  또한, 이후 단계에서 참조해야 하는 이름 필드 값도 기록해 둡니다.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
----
+

NOTE: 라는 선택적 필드가 있습니다. `fsType` 이 파일에 정의되어 있습니다.  이 줄은 NFS 백엔드에서 삭제할 수 있습니다.

. 실행하다 `kubectl` 저장 클래스를 생성하는 명령입니다.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. 스토리지 클래스가 생성되면 첫 번째 영구 볼륨 클레임(PVC)을 생성해야 합니다.  샘플이 있습니다 `pvc-basic.yaml` 이 작업을 수행하는 데 사용할 수 있는 파일도 sample-inputs에 있습니다.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi pvc-basic.yaml
----
. 이 파일에 대해 수행해야 하는 유일한 편집은 다음을 보장하는 것입니다. `storageClassName` 필드가 방금 만든 필드와 일치합니다.  PVC 정의는 프로비저닝할 작업 부하에 따라 추가로 사용자 정의할 수 있습니다.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. 다음을 실행하여 PVC를 생성합니다. `kubectl` 명령.  생성되는 백업 볼륨의 크기에 따라 생성에 시간이 걸릴 수 있으므로, 프로세스가 완료되는 모습을 지켜볼 수 있습니다.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-b4370d37-0fa4-4c17-bd86-94f96c94b42d   1Gi        RWO            basic-csi      7s
----

