---
sidebar: sidebar 
permalink: openshift/os-multitenancy-overview.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, Multitenancy, Multi-tenancy 
summary: NetApp 사용하여 Red Hat OpenShift에서 멀티테넌시 구성 
---
= NetApp 사용하여 Red Hat OpenShift에서 멀티테넌시 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
컨테이너에서 여러 애플리케이션이나 워크로드를 실행하는 많은 조직은 애플리케이션이나 워크로드당 하나의 Red Hat OpenShift 클러스터를 배포하는 경향이 있습니다.  이를 통해 애플리케이션이나 워크로드에 대한 엄격한 격리를 구현하고, 성능을 최적화하고, 보안 취약성을 줄일 수 있습니다.  그러나 각 애플리케이션에 별도의 Red Hat OpenShift 클러스터를 배포하면 고유한 문제가 발생합니다.  각 클러스터를 개별적으로 모니터링하고 관리해야 하므로 운영 오버헤드가 증가하고, 다양한 애플리케이션에 전용 리소스를 할당해야 하므로 비용이 증가하고, 효율적인 확장성이 방해를 받습니다.

이러한 문제를 극복하려면 모든 애플리케이션이나 워크로드를 단일 Red Hat OpenShift 클러스터에서 실행하는 것을 고려할 수 있습니다.  하지만 이러한 아키텍처에서는 리소스 격리와 애플리케이션 보안 취약성이 주요 과제 중 하나입니다.  한 작업 부하에서 발생하는 보안 취약점은 자연스럽게 다른 작업 부하로 확산되어 영향 범위가 넓어질 수 있습니다.  또한, 기본적으로 리소스 할당 정책이 없기 때문에 한 애플리케이션에서 갑자기 통제되지 않은 리소스 사용이 발생하면 다른 애플리케이션의 성능에 영향을 미칠 수 있습니다.

따라서 조직에서는 두 가지 장점을 모두 취할 수 있는 솔루션을 찾습니다. 예를 들어, 모든 워크로드를 단일 클러스터에서 실행하면서도 각 워크로드에 대해 전용 클러스터의 이점을 제공하는 것입니다.

이러한 효과적인 솔루션 중 하나는 Red Hat OpenShift에서 멀티테넌시를 구성하는 것입니다.  멀티테넌시는 여러 테넌트가 리소스, 보안 등을 적절히 분리하여 동일한 클러스터에 공존할 수 있도록 하는 아키텍처입니다.  이러한 맥락에서 테넌트는 특정 사용자 그룹이 독점적인 목적으로 사용하도록 구성된 클러스터 리소스의 하위 집합으로 볼 수 있습니다.  Red Hat OpenShift 클러스터에서 멀티테넌시를 구성하면 다음과 같은 이점이 있습니다.

* 클러스터 리소스를 공유함으로써 CapEx 및 OpEx 감소
* 운영 및 관리 비용 절감
* 보안 침해로 인한 교차 오염으로부터 작업 부하 보호
* 리소스 경합으로 인한 예상치 못한 성능 저하로부터 작업 부하 보호


완전히 구현된 멀티 테넌트 OpenShift 클러스터의 경우 컴퓨팅, 스토리지, 네트워킹, 보안 등 다양한 리소스 버킷에 속하는 클러스터 리소스에 대한 할당량과 제한을 구성해야 합니다.  이 솔루션에서는 모든 리소스 버킷의 특정 측면을 다루지만, NetApp ONTAP에서 지원하는 Trident 에서 동적으로 할당된 스토리지 NetApp 에 다중 테넌시를 구성하여 동일한 Red Hat OpenShift 클러스터에서 여러 워크로드가 제공하거나 사용하는 데이터를 격리하고 보호하기 위한 모범 사례에 중점을 ONTAP.
