---
sidebar: sidebar 
permalink: openshift/os-solution-overview.html 
keywords: NVA-1160, Red Hat, OpenShift, Netapp, Trident 
summary: '이 참조 문서는 NetApp 에서 검증한 대로 여러 다른 데이터 센터 환경에서 Installer Provisioned Infrastructure(IPI)를 통해 배포된 Red Hat OpenShift 솔루션의 배포 검증을 제공합니다.  또한, Trident 스토리지 오케스트레이터를 사용하여 영구 스토리지를 관리함으로써 NetApp 스토리지 시스템과의 스토리지 통합에 대해서도 자세히 설명합니다.  마지막으로, 여러 솔루션 검증과 실제 사용 사례를 탐색하고 문서화합니다.' 
---
= NVA-1160: NetApp 사용한 Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Alan Cowles와 Nikhil M Kulkarni, NetApp

[role="lead"]
이 참조 문서는 NetApp 에서 검증한 대로 여러 다른 데이터 센터 환경에서 Installer Provisioned Infrastructure(IPI)를 통해 배포된 Red Hat OpenShift 솔루션의 배포 검증을 제공합니다.  또한, Trident 스토리지 오케스트레이터를 사용하여 영구 스토리지를 관리함으로써 NetApp 스토리지 시스템과의 스토리지 통합에 대해서도 자세히 설명합니다.  마지막으로, 여러 솔루션 검증과 실제 사용 사례를 탐색하고 문서화합니다.



== 사용 사례

NetApp 솔루션이 포함된 Red Hat OpenShift는 다음과 같은 사용 사례를 가진 고객에게 탁월한 가치를 제공하도록 설계되었습니다.

* 베어 메탈, Red Hat OpenStack Platform, Red Hat Virtualization 및 VMware vSphere에서 IPI(Installer Provisioned Infrastructure)를 사용하여 배포된 Red Hat OpenShift는 쉽게 배포하고 관리할 수 있습니다.
* Red Hat OpenShift를 OSP, RHV 또는 vSphere에 가상으로 배포하거나 OpenShift 가상화를 통해 베어 메탈에 배포하여 엔터프라이즈 컨테이너와 가상화된 워크로드의 성능을 결합합니다.
* NetApp 스토리지와 Kubernetes를 위한 오픈소스 스토리지 오케스트레이터인 Trident 와 함께 사용할 때 Red Hat OpenShift의 기능을 강조하는 실제 구성 및 사용 사례입니다.




== 사업적 가치

기업들은 새로운 제품을 만들고, 출시 주기를 단축하고, 새로운 기능을 빠르게 추가하기 위해 DevOps 방식을 점점 더 많이 도입하고 있습니다.  컨테이너와 마이크로서비스는 본질적으로 민첩한 특성으로 인해 DevOps 실무를 지원하는 데 중요한 역할을 합니다.  그러나 기업 환경에서 프로덕션 규모로 DevOps를 실행하는 것은 고유한 과제를 제시하며, 다음과 같은 기본 인프라에 특정 요구 사항을 부과합니다.

* 스택의 모든 계층에서 높은 가용성
* 배포 절차의 용이성
* 중단 없는 운영 및 업그레이드
* 마이크로서비스 민첩성을 유지하기 위한 API 기반 및 프로그래밍 가능 인프라
* 성능 보장이 있는 멀티테넌시
* 가상화된 워크로드와 컨테이너화된 워크로드를 동시에 실행할 수 있는 기능
* 작업 부하 수요에 따라 인프라를 독립적으로 확장할 수 있는 기능


NetApp 이 탑재된 Red Hat OpenShift는 이러한 과제를 인식하고 고객이 선택한 데이터 센터 환경에서 RedHat OpenShift IPI의 완전 자동화된 배포를 구현하여 각 문제를 해결하는 솔루션을 제시합니다.



== 기술 개요

NetApp 솔루션이 포함된 Red Hat OpenShift는 다음과 같은 주요 구성 요소로 구성됩니다.



=== Red Hat OpenShift 컨테이너 플랫폼

Red Hat OpenShift Container Platform은 완벽하게 지원되는 엔터프라이즈 Kubernetes 플랫폼입니다.  Red Hat은 컨테이너화된 애플리케이션을 빌드, 배포 및 관리하기 위한 모든 구성 요소가 완벽하게 통합된 애플리케이션 플랫폼을 제공하기 위해 오픈 소스 Kubernetes에 여러 가지 개선 사항을 적용했습니다.

자세한 내용은 OpenShift 웹사이트를 방문하세요. https://www.openshift.com["여기"] .



=== NetApp 스토리지 시스템

NetApp 기업 데이터 센터와 하이브리드 클라우드 구축에 적합한 여러 가지 스토리지 시스템을 보유하고 있습니다.  NetApp 포트폴리오에는 NetApp ONTAP, NetApp Element, NetApp e-Series 스토리지 시스템이 포함되어 있으며, 이 모든 시스템은 컨테이너화된 애플리케이션에 대한 영구 스토리지를 제공할 수 있습니다.

자세한 내용은 NetApp 웹사이트를 방문하세요. https://www.netapp.com["여기"] .



=== NetApp 스토리지 통합

Trident Red Hat OpenShift를 포함한 컨테이너와 Kubernetes 배포판을 위한 오픈 소스이자 완벽하게 지원되는 스토리지 오케스트레이터입니다.

자세한 내용은 Trident 웹사이트를 방문하세요. https://docs.netapp.com/us-en/trident/index.html["여기"] .



== 고급 구성 옵션

이 섹션에서는 전용 개인 이미지 레지스트리를 만들거나 사용자 정의 로드 밸런서 인스턴스를 배포하는 등 실제 사용자가 이 솔루션을 프로덕션에 배포할 때 수행해야 할 가능성이 높은 사용자 정의에 대해 설명합니다.



== 검증된 릴리스에 대한 현재 지원 매트릭스

|===


| 기술 | 목적 | 소프트웨어 버전 


| NetApp ONTAP | 스토리지 | 9.8, 9.9.1, 9.12.1 


| NetApp Element | 스토리지 | 12.3 


| NetApp Trident | 스토리지 오케스트레이션 | 22.01.0, 23.04, 23.07, 23.10, 24.02 


| 레드햇 오픈시프트 | 컨테이너 오케스트레이션 | 4.6 유럽, 4.7, 4.8, 4.10, 4.11, 4.12, 4.13, 4.14 


| VMware vSphere | 데이터 센터 가상화 | 7.0, 8.0.2 
|===